{
    "name": "Specific Contracts",
    "version": "17.0.1.0.0",
    "category": "Services",
    "summary": "Specific contracts with service lines, invoicing integration, and custom reports",
    "description": "Allows creating and managing specific contracts that reference signed master contracts.",
    "author": "Osliani Figueiras Saucedo",
    "depends": [
        "base",
        "contacts",
        "account",
        "product",
        "uom",
        "contratos",
        "partner_custom_fields",
        "telegram_notifier",
    ],
    "post_init_hook": "post_init_hook",
    "uninstall_hook": "uninstall_hook",
    "data": [
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "data/specific_template_data.xml",
        "wizard/contrato_especifico_cancel_wizard_views.xml",
        "wizard/contrato_especifico_facturar_wizard_views.xml",
        "views/contrato_especifico_import_wizard_views.xml",
        "views/contrato_especifico_template_views.xml",
        "views/contrato_especifico_ueb_section_views.xml",
        "views/contrato_especifico_suplemento_views.xml",
        "views/contrato_especifico_views.xml",
        "report/contrato_especifico_reports.xml",
    ],
    "installable": True,
    "application": False,
    "license": "LGPL-3",
    "assets": {
        "web.assets_backend": [
            "contratos_especificos/static/src/suplemento_redirect_service.js",
        ],
    },
}
